<a href="https://colab.research.google.com/github/bankarrohan09/Python/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy

Basic Operation

In [ ]:
#import packagename as nickname
import numpy as np

In [ ]:
n1 = np.array([1,2,3,4])

In [ ]:
print( type(n1) )

<class 'numpy.ndarray'>


In [ ]:
print (n1.ndim, n1.shape)

1 (4,)


In [ ]:
n1

array([1, 2, 3, 4])

In [ ]:
n2 = np.array(
    [
    [1,2,3,4],
    [9,8,7,6]
    ]
)

In [ ]:
print(n2.ndim, n2.shape)
print(n2)

2 (2, 4)
[[1 2 3 4]
 [9 8 7 6]]


In [ ]:
n3 = n2 + 3

In [ ]:
n10 = np.ones(shape=(2,3))
n10

array([[1., 1., 1.],
       [1., 1., 1.]])

Indexing, slicing

In [ ]:
n2

array([[1, 2, 3, 4],
       [9, 8, 7, 6]])

In [ ]:
print(n2[1,1])

8


In [ ]:
print(n2[1,1:3])

[8 7]


In [ ]:
n3 = n2.T
n3

array([[1, 9],
       [2, 8],
       [3, 7],
       [4, 6]])

In [ ]:
#n3[1:3, ]
#n3[1:3]
n3[1:3, :]

array([[2, 8],
       [3, 7]])

In [ ]:
a1 = range(6)
print(type(a1),a1)

<class 'range'> range(0, 6)


In [ ]:
n11 = np.arange(6)
print(type(n11))
print(n11)

<class 'numpy.ndarray'>
[0 1 2 3 4 5]


In [ ]:
n12 = np.arange(5,16,2)
print(n12)

[ 5  7  9 11 13 15]


In [ ]:
n13 = n12.reshape(2,3)
print(n13)

[[ 5  7  9]
 [11 13 15]]


In [ ]:
#put all this together
n21 = np.arange(8).reshape(2,4)
print(n21)

[[0 1 2 3]
 [4 5 6 7]]


In [ ]:
n22 = np.arange(24).reshape(2,3,4)
print(n22)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
print(n22[1,2,3])
#show first column of each 2D array
#n22 [0:2,:,0]
#n22 [: , : , 0]
n22[...,0]

23


array([[ 0,  4,  8],
       [12, 16, 20]])

In [ ]:
print(n22)
print(n22[0,...])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
#output 3,1,2
print(n21[0,1:4])
print(n21[0,[3,1,2]]) #slicing for not contigous elements provide list

[1 2 3]
[3 1 2]


In [ ]:
print(n21[n21>2])

[3 4 5 6 7]


In [ ]:
print(n21[n21>2 and n21<8])

ValueError: ignored

In [ ]:
a = 10
a>15 and a<20

False

Basic arithmetic operations

In [ ]:
import numpy as np
n1 = np.arange(6).reshape(2,3)
n1

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
n1 ** 3

array([[  0,   1,   8],
       [ 27,  64, 125]])

In [ ]:
n2 = np.arange(10,16).reshape(2,3)
n2

array([[10, 11, 12],
       [13, 14, 15]])

In [ ]:
print(n2)
print(n2.max(),n2.min())

[[10 11 12]
 [13 14 15]]
15 10


In [ ]:
print(n2.max(axis=1),n2.max(axis=0))
#axis 0 is column wise, axis 1 is row wise

[12 15] [13 14 15]


In [ ]:
n1 = np.arange(6).reshape(2,3)
n1

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
print (id(n1[0][0]), " - ",n1[0][0],"\n",id(n1[0][1]), " -",n1[0][1],"\n",)
print (id(n1[0][2]), " - ",n1[0][2],"\n",id(n1[1][0]), " -",n1[1][0],"\n",)
print (id(n1[1][1]), " - ",n1[1][1],"\n",id(n1[1][2]), " -",n1[1][2],"\n",)

139999486162544  -  0 
 139999486163152  - 1 

139999486164496  -  2 
 139999486164304  - 3 

139999486163344  -  4 
 139999486163408  - 5 



In [ ]:
n2 = np.arange(6)
n2
for i in n2:
  print(id(i), " - ",i)

139999482796944  -  0
139999482796240  -  1
139999482796944  -  2
139999482796240  -  3
139999482796944  -  4
139999482796240  -  5


Operations

In [ ]:
import numpy as np
n1 = np.arange(10).reshape(2,5)

In [ ]:
n1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
for i in n1[0]:
  print(i)

0
1
2
3
4


In [ ]:
n1[0]

array([0, 1, 2, 3, 4])

In [ ]:
n2 = np.array([10,20,15,10,25,15])
#output [10,20,15,25]

In [ ]:
#make one new empty array
#take one element from n1 array and add it to new empty array
#if that element is not present in target
n2 = np.array([10,20,15,10,25,15])
n2new = []
for i in n2:
  #check i is in n2new array or not
  if i not in n2new:
    n2new.append(i)

n2new

[10, 20, 15, 25]

In [ ]:
n2 = [10,20,15,10,25,15]
# show the count of each element in the array
# 10 - 2
# 20 - 1
# 15 - 2
# 25 - 1
# pic first element from given list and
# check all other elements -
# if it match count++

In [ ]:
n2 = [10,20,15,10,25,15]
for i in n2:
  count = 0
  for j in n2:
    if i==j:
      count += 1
  print(i," : ",count)

10  :  2
20  :  1
15  :  2
10  :  2
25  :  1
15  :  2


In [ ]:
n2 = [10,20,15,10,25,15]
#create blank dictionary
for i in n2:
  #add element to dictonary as key and value as 1(representing count)
  #if the element is existing as key then increment the value (representing count)
  count = 0
  if i==j:
    count += 1
  print(i," : ",count)

10  :  0
20  :  0
15  :  1
10  :  0
25  :  0
15  :  1


In [ ]:
n3 = {}
for i in n2:
  if i not in n3:
    n3[i] = 1
  else:
    n3[i] += 1
print(n3)

{10: 2, 20: 1, 15: 2, 25: 1}


Exercise

1. Write logic to display the binary equivalent of given decimal no

In [ ]:
# To get a binary of a number we divide the number by 2 and rewrite the remainders obtained from last to first
# till we can divide it no further or remainder is 0
# we take quotients into the loop
s1 =" "
n1 =14 ; #print(n1)
r = n1%2  ; print(r); s1 = str(r)+s1
n1 = n1//2 ; #print(n1)
r = n1%2  ; print(r); s1 = str(r)+s1
n1 = n1//2 ; #print(n1)
r = n1%2  ; print(r) ; s1 = str(r)+s1
n1 = n1//2 ; #print(n1)
r = n1%2  ; print(r); s1 = str(r)+s1
print(s1)

0
1
1
1
1110 


2. Write logic to display the sum of digits given decimal no

In [ ]:
n1 = 352
sum = 0
t = n1 % 10   #display 2
t1 = n1 // 10   #display 35
t2 = t1 % 10   #display 5
t3 = n1 // 100   #display 3
sum = t + t2 + t3
print(sum)

10


3. Write logic to display the greatest number in the given list

In [ ]:
n1 = [10,30,50,23,41,13]
max = n1[0]
for i in n1:
  if i>max:
    max = i
print(max)

50


Universal functions

In [ ]:
import numpy as np
n1 = np.arange(10).reshape(2,5)
print(n1)
n2 = np.arange(3,13,1).reshape(2,5)
print(n2)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 3  4  5  6  7]
 [ 8  9 10 11 12]]


In [ ]:
n3 = n1+ n2
print(n3)

[[ 3  5  7  9 11]
 [13 15 17 19 21]]


In [ ]:
n4 = np.add(n1,n2)
print(n4)

[[ 3  5  7  9 11]
 [13 15 17 19 21]]


In [ ]:
print(n1,np.sqrt(n1))

[[0 1 2 3 4]
 [5 6 7 8 9]] [[0.         1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712 3.        ]]


Broadcasting

In [ ]:
import numpy as np
n1 = np.arange(6,8)
print(n1)

[6 7]


In [ ]:
n2 = np.arange(10,14).reshape(2,2)
print(n2)

[[10 11]
 [12 13]]


In [ ]:
n3 = n1 + n2
print(n3)

[[16 18]
 [18 20]]


In [ ]:
n4 = np.arange(10,16).reshape(3,2)
print(n4)

[[10 11]
 [12 13]
 [14 15]]


In [ ]:
n5 = n4 + n1
print(n5)

[[16 18]
 [18 20]
 [20 22]]


In [ ]:
n11 = np.arange(10,13).reshape(3,1)
print(n11)

[[10]
 [11]
 [12]]


In [ ]:
print(n11 + n5)

[[26 28]
 [29 31]
 [32 34]]


In [ ]:
n12 = np.arange(10,12).reshape(2,1)
print(n12)

[[10]
 [11]]


In [ ]:
print(n12 + n5)

ValueError: ignored

In [ ]:
print(n5)
n6 = np.arange(10,22).reshape(3,4)
print(n6)
print(n5+n6)

[[16 18]
 [18 20]
 [20 22]]
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


ValueError: ignored

In [ ]:
print(n6)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [ ]:
#print(n6[0])
n6[2] = [[18,19,20,21] , [7,8,9,34]]
print(n6)

ValueError: ignored

In [ ]:
a = 10
print(a," ",id(a))
b = a
print(b," ",id(b))
c = 10
print(c," ",id(c))

10   137624059281936
10   137624059281936
10   137624059281936


Computational efficiency

In [ ]:
def digits(n1):
  sum = 0
  while (n1>0):
    r = n1 % 10
    sum = sum + r
    n1 = n1 // 10
  print(sum)

In [ ]:
digits(9318786654)

57


In [ ]:
%timeit digits(64321103)

Streaming output truncated to the last 5000 lines.
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
2